### ISSUE TITLE
python code is not working

### ISSUE THREAD

**Issue by Masik84** [KhamisiKibet/QT-PyQt-PySide-Custom-Widgets#15]
Hi, I've installed QT-PyQt-PySide-Custom-Widgets as you show in your video and this is in your file "SOURCES.txt". 
But there is an error and I can't open any examples. It's always shows an error that some imports are impossible.

Then I tried to run the code which you put into file "SOURCES.txt" and have an error. Could you help please?
"from Custom_Widgets.ProgressIndicator import test
test.main()"

There is a full text of error in attached file

[QT-PyQt-PySide_Custome_Widgets _ error.txt](https://github.com/KhamisiKibet/QT-PyQt-PySide-Custom-Widgets/files/8556694/QT-PyQt-PySide_Custome_Widgets._.error.txt)

**Comment by fefedelcid** [comment]
```python
from collections import Mapping, Sequence
```
`ImportError: cannot import name 'Mapping' from 'collections' ([...]\lib\collections\__init__.py)`
If you use a virtual environment the same error happens in `\lib\site-packages\qtsass\api.py`

The `Mapping` and `Sequence` classes are defined in `typing`, so changing the lines
```python
from collections import Mapping, Sequence
```
by
```python
from typing import Mapping, Sequence
```
the problem is solved.

**Comment by KhamisiKibet** [comment]
That's mapping import error, the solution is already in Stack overflow,
just google the last few lines of the 'mapping' import error
